from app.services.frontend_api_service import (
    get_calendar_events,
    get_latest_newsletter,
    get_success2_catalog,
    get_success_catalog,
    get_success_leaderboard,
    get_unlocked_successes,
)
from app.services.claim_service import create_success_claim
from app.services.success_validation_service import (
    approve_validation,
    create_validation_request,
    find_success,
    get_validation_channel,
    get_validation_request,
    get_user_validation_history,
    refuse_validation,
    set_validation_channel,
)
from app.services.user_registration_service import create_registered_user
from app.services.user_service import (
    add_user_secondary_class,
    delete_user_picture,
    get_total_season2_tickets,
    get_user_birthday,
    get_user_by_token,
    get_user_classes,
    get_user_picture,
    get_user_presentation,
    remove_user_secondary_class,
    update_user_birthday,
    update_user_class,
    update_user_picture,
    update_user_presentation,
    update_user_secondary_classes,
    get_user_profile,
)

__all__ = [
    "add_user_secondary_class",
    "approve_validation",
    "create_registered_user",
    "create_success_claim",
    "create_validation_request",
    "delete_user_picture",
    "find_success",
    "get_calendar_events",
    "get_latest_newsletter",
    "get_success2_catalog",
    "get_success_catalog",
    "get_success_leaderboard",
    "get_total_season2_tickets",
    "get_unlocked_successes",
    "get_user_birthday",
    "get_user_by_token",
    "get_user_classes",
    "get_user_picture",
    "get_user_presentation",
    "get_user_profile",
    "get_validation_channel",
    "get_validation_request",
    "get_user_validation_history",
    "refuse_validation",
    "remove_user_secondary_class",
    "set_validation_channel",
    "update_user_birthday",
    "update_user_class",
    "update_user_picture",
    "update_user_presentation",
    "update_user_secondary_classes",
]
